// frontend/src/Dashboard.svelte
<script lang="ts">
  import StatsCards from "./components/StatsCards.svelte";
  import UpcomingActions from "./components/UpcomingActions.svelte";
  import CollectionsSidebar from "./components/CollectionsSidebar.svelte";
  import Filters from "./components/Filters.svelte";
  import BillTable from "./components/BillTable.svelte";
  import { createBills } from "@/hooks/use-bills.svelte";
  import { createStats } from "@/hooks/use-stats.svelte";
  import { createCities } from "@/hooks/use-cities.svelte";
  import { createTopics } from "@/hooks/use-topics.svelte";
  import { createUpcoming } from "@/hooks/use-upcoming.svelte";
  import { useErrorToast } from "@/hooks/use-error-toast.svelte";

  let { refreshKey = 0 }: { refreshKey?: number } = $props();

  const keyRef = () => refreshKey;
  const billsStore = createBills(keyRef);
  const statsStore = createStats(keyRef);
  const { cities } = createCities();
  const { topics } = createTopics();
  const upcomingStore = createUpcoming(keyRef);

  useErrorToast(billsStore.error, "Failed to load bills");
  useErrorToast(statsStore.error, "Failed to load stats");
  useErrorToast(upcomingStore.error, "Failed to load upcoming bills");
</script>

<main class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
  <StatsCards stats={statsStore.stats} loading={statsStore.loading} />
  <UpcomingActions bills={upcomingStore.bills} loading={upcomingStore.loading} />
  <CollectionsSidebar />
  <Filters
    filters={billsStore.filters}
    cities={cities}
    topics={topics}
    onChange={(f) => billsStore.setFilters(f)}
  />

  {#if billsStore.error}
    <div class="mb-4 rounded-lg bg-destructive/10 border border-destructive/20 p-4 text-sm text-destructive">
      {billsStore.error}
    </div>
  {/if}

  <BillTable
    bills={billsStore.bills}
    total={billsStore.total}
    page={billsStore.page}
    perPage={billsStore.perPage}
    onPageChange={(p: number) => (billsStore.page = p)}
    loading={billsStore.loading}
  />
</main>

// frontend-react/src/components/Dashboard.tsx
import StatsCards from "./StatsCards";
import UpcomingActions from "./UpcomingActions";
import CollectionsSidebar from "./CollectionsSidebar";
import Filters from "./Filters";
import BillTable from "./BillTable";
import { useBills } from "../hooks/useBills";
import { useStats } from "../hooks/useStats";
import { useCities } from "../hooks/useCities";
import { useTopics } from "../hooks/useTopics";
import { useUpcoming } from "../hooks/useUpcoming";
import { useErrorToast } from "../hooks/useErrorToast";

interface DashboardProps {
  refreshKey: number;
}

function Dashboard({ refreshKey }: DashboardProps) {
  const { bills, total, page, perPage, filters, loading: loadingBills, error, setPage, setFilters } = useBills(refreshKey);
  const { stats, loading: loadingStats, error: statsError } = useStats(refreshKey);
  const cities = useCities();
  const topics = useTopics();
  const { bills: upcomingBills, loading: loadingUpcoming, error: upcomingError } = useUpcoming(refreshKey);

  useErrorToast(error, "Failed to load bills");
  useErrorToast(statsError, "Failed to load stats");
  useErrorToast(upcomingError, "Failed to load upcoming bills");

  return (
    <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
      <StatsCards stats={stats} loading={loadingStats} />
      <UpcomingActions bills={upcomingBills} loading={loadingUpcoming} />
      <CollectionsSidebar />
      <Filters
        filters={filters}
        cities={cities}
        topics={topics}
        onChange={setFilters}
      />

      {error && (
        <div className="mb-4 rounded-lg bg-destructive/10 border border-destructive/20 p-4 text-sm text-destructive">
          {error}
        </div>
      )}

      <BillTable
        bills={bills}
        total={total}
        page={page}
        perPage={perPage}
        onPageChange={setPage}
        loading={loadingBills}
      />
    </main>
  );
}

export default Dashboard;
