// frontend-svelte/src/components/briefing/BriefingNotes.svelte
<script lang="ts">
  let { notes }: { notes: { collection_name: string; note: string }[] } = $props();
</script>

{#if notes.length > 0}
  <div class="p-4 sm:p-6 bg-muted border-l-4 border-primary">
    <h4 class="text-xs font-bold text-muted-foreground uppercase tracking-wider mb-3">Organizer Notes</h4>
    <div class="space-y-2">
      {#each notes as note}
        <div>
          <span class="text-xs font-medium text-primary">{note.collection_name}:</span>
          <p class="text-sm text-foreground leading-relaxed mt-0.5">{note.note}</p>
        </div>
      {/each}
    </div>
  </div>
{/if}

// frontend-react/src/components/briefing/BriefingNotes.tsx
interface BriefingNotesProps {
  notes: { collection_name: string; note: string }[];
}

export function BriefingNotes({ notes }: BriefingNotesProps) {
  if (notes.length === 0) return null;
  return (
    <div className="p-4 sm:p-6 bg-muted border-l-4 border-primary">
      <h4 className="text-xs font-bold text-muted-foreground uppercase tracking-wider mb-3">
        Organizer Notes
      </h4>
      <div className="space-y-2">
        {notes.map((note, i) => (
          <div key={i}>
            <span className="text-xs font-medium text-primary">{note.collection_name}:</span>
            <p className="text-sm text-foreground leading-relaxed mt-0.5">{note.note}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
